### ISSUE TITLE
Stella of the End

### ISSUE THREAD

**Issue by mailwl** [xmoezzz/artemis_ast#1]
Error:

Extracting secnario text from 01_stella_01_1.ast to 01_stella_01_1.txt
thread 'main' panicked at src/main.rs:615:40:
called `Result::unwrap()` on an `Err` value: Unexpected character: ]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

in file only text has [] symbols:

			en = {
				{
					[["Great, another one."]],
				},

**Comment by xmoezzz** [comment]
Can you provide some samples?

**Comment by mailwl** [comment]
[st01.zip](https://github.com/xmoezzz/artemis_ast/files/13304968/st01.zip)

**Comment by Aleisster** [comment]
Same error here: 
thread 'main' panicked at src\main.rs:615:40:
called `Result::unwrap()` on an `Err` value: Unexpected character: -
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[01_c_00.zip](https://github.com/xmoezzz/artemis_ast/files/13404355/01_c_00.zip)
